In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Load dataset
Data_Set = load_iris()
features = Data_Set["data"]
target = Data_Set["target"]

# One-Hot Encode target
Target = target.reshape(150, 1)
OHE = OneHotEncoder(sparse_output=False)
New_Target = OHE.fit_transform(Target)

# Split data
x_train, x_test, y_train, y_test = train_test_split(features, New_Target, train_size=0.8, random_state=42)

# Create and train Decision Tree Classifier
DT_Model = DecisionTreeClassifier(random_state=42)
DT_Model.fit(x_train, y_train)

# Predict on test data
y_pred = DT_Model.predict(x_test)

# Since we used one-hot encoding, convert back to class labels for evaluation
y_test_labels = np.argmax(y_test, axis=1)
y_pred_labels = np.argmax(y_pred, axis=1)

# Calculate accuracy
accuracy = accuracy_score(y_test_labels, y_pred_labels)

# Create confusion matrix
cm = confusion_matrix(y_test_labels, y_pred_labels)

# Display results
print("Decision Tree Classifier Accuracy:", accuracy)
print("Confusion Matrix:\n", cm)


Decision Tree Classifier Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense 
from tensorflow.keras.models import Sequential


ModuleNotFoundError: No module named 'tensorflow.python'

In [ ]:
Model = Sequential([
    Dense(16,input_shape=(4,))
])